# nixpacks.toml
[phases.setup]
nixPkgs = [
  "chromium",
  "alsa-lib",
  "at-spi2-atk",
  "atk",
  "cairo",
  "cups",
  "dbus-glib",
  "pango",
  "nss",
  "libXcomposite",
  "libXcursor",
  "libXdamage",
  "libXi",
  "libXinerama",
  "libXrandr",
  "xdg-utils"
]
