[phases.setup]
aptPkgs = [
  "chromium-browser",
  "fonts-liberation",
  "gconf-service",
  "libappindicator1",
  "libasound2",
  "libatk1.0-0",
  "libcairo2",
  "libcups2",
  "libdbus-1-3",
  "libgconf-2-4",
  "libnspr4",
  "libnss3",
  "libpango1.0-0",
  "libxss1",
  "lsb-release",
  "xdg-utils"
]
