# nixpacks.toml

[phases.setup]
nixPkgs = [
  "chromium",      # <-- Tells Nixpacks to install system Chromium
  "alsa-lib",
  "at-spi2-atk",
  "atk",
  "cairo",
  "cups",
  "dbus-glib",
  "pango",
  "nss",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libxi",
  "libxcursor",
  "libxinerama",
  "xdg-utils"
]
